M48
; DRILL file {KiCad 8.0.1} date 2024-04-28T13:44:50+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-28T13:44:50+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1280
%
G90
G05
T1
X4.0264Y-3.4449
X4.4398Y-3.4449
T2
X4.0945Y-2.6969
X4.0945Y-4.1929
T3
X7.4544Y-2.97
X7.4544Y-3.42
M30
